version: "3.9"
   
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vivid_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - vivid-network

  backend:
    container_name: django
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - static:/app/backend/static
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
    networks:
      - vivid-network
    links:
      - db
    depends_on:
      - db
  webapp:
    container_name: nextjs
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - vivid-network
    command:
      "npm start"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - node-modules:/app/webapp/node_modules
    links:
      - backend
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: devops/nginx
      dockerfile: Dockerfile
    volumes:
      - static:/app/backend/static
    ports:
      - 8080:8080
    links: 
      - backend
      - webapp
    networks:
      - vivid-network
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  db:
  node-modules:
  static:

networks:
  vivid-network: